ALTER TABLE users ADD COLUMN IF NOT EXISTS app_version_code INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS app_version_name TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS app_version_at TIMESTAMPTZ;
